/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import entidades.Comprador;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencias.CompradorData;

/**
 *
 * @author pc
 */
public class AdmiCompradores extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdmiCompradores
     */
    DefaultTableModel modeloTabla = new DefaultTableModel();
    CompradorData compradorD = new CompradorData();
    public AdmiCompradores() {
        initComponents();
        cargarCombo();
        cargarColumnas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jpDatos = new javax.swing.JPanel();
        jlDni = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlNac = new javax.swing.JLabel();
        jlPass = new javax.swing.JLabel();
        jlMedioPago = new javax.swing.JLabel();
        jtfDni = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jtfPassword = new javax.swing.JTextField();
        jtfMedioPago = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCompradores = new javax.swing.JTable();
        jdcFechaNac = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jcbOpciones = new javax.swing.JComboBox<>();
        jbGuardar = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();
        jbBorrar = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jlTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo.setText("Complete sus datos");

        jpDatos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 51, 255)));

        jlDni.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jlDni.setForeground(new java.awt.Color(0, 0, 102));
        jlDni.setText("Dni:");

        jlNombre.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jlNombre.setForeground(new java.awt.Color(0, 0, 102));
        jlNombre.setText("Nombre:");

        jlNac.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jlNac.setForeground(new java.awt.Color(0, 0, 102));
        jlNac.setText("Fecha de nac:");

        jlPass.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jlPass.setForeground(new java.awt.Color(0, 0, 102));
        jlPass.setText("Password:");

        jlMedioPago.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jlMedioPago.setForeground(new java.awt.Color(0, 0, 102));
        jlMedioPago.setText("Medio de pago:");

        jtfDni.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 51, 204)));
        jtfDni.setCaretColor(new java.awt.Color(0, 51, 204));

        jtfNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 51, 204)));

        jtfPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 51, 204)));
        jtfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPasswordActionPerformed(evt);
            }
        });

        jtfMedioPago.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 51, 204)));

        jtCompradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtCompradores);

        jLabel1.setText("Elija una opcion:");

        jcbOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbOpcionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpDatosLayout = new javax.swing.GroupLayout(jpDatos);
        jpDatos.setLayout(jpDatosLayout);
        jpDatosLayout.setHorizontalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDatosLayout.createSequentialGroup()
                        .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jpDatosLayout.createSequentialGroup()
                                .addComponent(jlPass)
                                .addGap(44, 44, 44)
                                .addComponent(jtfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpDatosLayout.createSequentialGroup()
                                .addComponent(jlNac)
                                .addGap(18, 18, 18)
                                .addComponent(jdcFechaNac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jpDatosLayout.createSequentialGroup()
                                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDatosLayout.createSequentialGroup()
                                        .addComponent(jlDni)
                                        .addGap(90, 90, 90))
                                    .addGroup(jpDatosLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfDni)
                                    .addComponent(jcbOpciones, 0, 228, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDatosLayout.createSequentialGroup()
                                .addComponent(jlNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpDatosLayout.createSequentialGroup()
                                .addComponent(jlMedioPago)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfMedioPago, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jpDatosLayout.setVerticalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDatosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jcbOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlDni)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNombre))
                .addGap(30, 30, 30)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDatosLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlNac)
                            .addComponent(jdcFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlPass)))
                    .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtfMedioPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jpDatosLayout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(jlMedioPago))))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jbGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/new_file_add_paper_icon_231603.png"))); // NOI18N
        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/zoom_magnyfying_glass_search_icon_231650.png"))); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pen_pencil_write_edit_icon_231611 (1).png"))); // NOI18N
        jbActualizar.setText("Actualizar");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jbBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/trash_can_rubish_paper_bin_icon_231400.png"))); // NOI18N
        jbBorrar.setText("Borrar");
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });

        Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/brush_paint_icon_231542.png"))); // NOI18N
        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jlTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbGuardar)
                                .addGap(28, 28, 28)
                                .addComponent(jbBuscar)
                                .addGap(28, 28, 28)
                                .addComponent(jbActualizar)
                                .addGap(28, 28, 28)
                                .addComponent(jbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(Limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jpDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jpDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPasswordActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        //Validacion de campos vacios
        if(jtfDni.getText().trim().isEmpty() || jtfNombre.getText().trim().isEmpty()
            || jdcFechaNac.getDate() == null || jtfPassword.getText().trim().isEmpty() ||
            jtfMedioPago.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Los campos no pueden estar vacios");
            return;
        }
        
        try {
            int dni = Integer.parseInt(jtfDni.getText());
            String nombre = jtfNombre.getText();
            LocalDate fechaNac = jdcFechaNac.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            String password = jtfPassword.getText();
            String medioPago = jtfMedioPago.getText();

            Comprador comprador = new Comprador(dni, nombre, fechaNac, password, medioPago);
            compradorD.RegistrarComprador(comprador);
            JOptionPane.showMessageDialog(this, "Comprador Guardado");
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Error de formato");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        //Validacion de campos vacios
        if(jtfDni.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "El campo no puede estar vacio");
            return;
        }
        try {
            int dni = Integer.parseInt(jtfDni.getText());
            Comprador comprador = new Comprador();
            comprador = compradorD.buscarComprador(dni);
            modeloTabla.addRow(new Object[] {
                comprador.getDniComprador(),
                comprador.getNombre(),
                comprador.getFechaNacimiento(),
                comprador.getPassword(),
                comprador.getMedioDePago()
        });
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Error de formato");
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(this, "El comprador no existe");
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        //Validacion de campos vacios
        if(jtfDni.getText().trim().isEmpty() || jtfNombre.getText().trim().isEmpty()
            || jdcFechaNac.getDate() == null || jtfPassword.getText().trim().isEmpty() ||
            jtfMedioPago.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Los campos no pueden estar vacios");
            return;
        }
        
        try {
            int dniComprador = Integer.parseInt(jtfDni.getText());
            String nombre = jtfNombre.getText();
            LocalDate fechaNac = jdcFechaNac.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            String password = jtfPassword.getText();
            String medioPago = jtfMedioPago.getText();

            Comprador comprador = new Comprador(dniComprador, nombre, fechaNac, password, medioPago);

            compradorD.actualizarComprador(comprador);
            JOptionPane.showMessageDialog(this, "Comprador Actualizado");
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Error de formato" + e.getMessage());
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(this, "El comprador no existe");
        }
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        //Validacion de campos vacios
        if(jtfDni.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "El campo no puede estar vacio");
            return;
        }
        try{
            int dniComprador = Integer.parseInt(jtfDni.getText());     
            compradorD.bajaFisica(dniComprador);
            JOptionPane.showMessageDialog(this, "Comprador Borrado");
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Error de formato" + e.getMessage());
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(this, "El comprador no existe");
        }    
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        jtfDni.setText("");
        jtfNombre.setText("");
        jdcFechaNac.setDate(null);
        jtfPassword.setText("");
        jtfMedioPago.setText("");
        modeloTabla.setRowCount(0);
    }//GEN-LAST:event_LimpiarActionPerformed

    private void jcbOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbOpcionesActionPerformed
        String opciones = (String)jcbOpciones.getSelectedItem();
        switch(opciones){
            case "Guardar":
                jtfDni.setEnabled(true);
                jtfNombre.setEnabled(true);
                jdcFechaNac.setEnabled(true);
                jtfPassword.setEnabled(true);
                jtfMedioPago.setEnabled(true);
                jbGuardar.setEnabled(true);
                jbBuscar.setEnabled(false);
                jbActualizar.setEnabled(false);
                jbBorrar.setEnabled(false);
                break;
            case "Buscar":
                jtfDni.setEnabled(true);
                jtfNombre.setEnabled(false);
                jdcFechaNac.setEnabled(false);
                jtfPassword.setEnabled(false);
                jtfMedioPago.setEnabled(false);
                jbGuardar.setEnabled(false);
                jbBuscar.setEnabled(true);
                jbActualizar.setEnabled(false);
                jbBorrar.setEnabled(false);
                break;
            case "Actualizar":
                jtfDni.setEnabled(true);
                jtfNombre.setEnabled(true);
                jdcFechaNac.setEnabled(true);
                jtfPassword.setEnabled(true);
                jtfMedioPago.setEnabled(true);
                jbGuardar.setEnabled(false);
                jbBuscar.setEnabled(false);
                jbActualizar.setEnabled(true);
                jbBorrar.setEnabled(false);                
                break;
            case "Borrar":
                jtfDni.setEnabled(true);
                jtfNombre.setEnabled(false);
                jdcFechaNac.setEnabled(false);
                jtfPassword.setEnabled(false);
                jtfMedioPago.setEnabled(false);
                jbGuardar.setEnabled(false);
                jbBuscar.setEnabled(false);
                jbActualizar.setEnabled(false);
                jbBorrar.setEnabled(true);
                break;
        }
    }//GEN-LAST:event_jcbOpcionesActionPerformed

    public void cargarCombo(){
        jcbOpciones.addItem("Guardar");
        jcbOpciones.addItem("Buscar");
        jcbOpciones.addItem("Actualizar");
        jcbOpciones.addItem("Borrar");
    }
    
    public void cargarColumnas(){
        modeloTabla.addColumn("Dni");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Fecha de nacimiento");
        modeloTabla.addColumn("Password");
        modeloTabla.addColumn("Medio de pago");
        jtCompradores.setModel(modeloTabla);
    }
    
    public void cargarFilas(){
        int dni = Integer.parseInt(jtfDni.getText());
        Comprador comprador = new Comprador();
        comprador = compradorD.buscarComprador(dni);
        modeloTabla.addRow(new Object[] {
            comprador.getDniComprador(),
            comprador.getNombre(),
            comprador.getFechaNacimiento(),
            comprador.getPassword(),
            comprador.getMedioDePago()
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JComboBox<String> jcbOpciones;
    private com.toedter.calendar.JDateChooser jdcFechaNac;
    private javax.swing.JLabel jlDni;
    private javax.swing.JLabel jlMedioPago;
    private javax.swing.JLabel jlNac;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlPass;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JPanel jpDatos;
    private javax.swing.JTable jtCompradores;
    private javax.swing.JTextField jtfDni;
    private javax.swing.JTextField jtfMedioPago;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfPassword;
    // End of variables declaration//GEN-END:variables
}
