/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import entidades.LugarAsiento;
import entidades.Proyeccion;
import javax.swing.JOptionPane;
import persistencias.LugarData;

/**
 *
 * @author pc
 */
public class AdmiLugares extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdmiLugares
     */
    LugarData lugarD = new LugarData();
    public AdmiLugares() {
        initComponents();
        cargarOpciones();
        cargarEstado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcbOpciones = new javax.swing.JComboBox<>();
        Opciones = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfIdLugar = new javax.swing.JTextField();
        jlFila = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfFila = new javax.swing.JTextField();
        jtfColumna = new javax.swing.JTextField();
        jtfIdProyeccion = new javax.swing.JTextField();
        jcbEstado = new javax.swing.JComboBox<>();
        jbGuardar = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();
        jbBorrar = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel1.setText("Administracion Lugares");

        jcbOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbOpcionesActionPerformed(evt);
            }
        });

        Opciones.setText("Opciones");

        jLabel2.setText("IdLugar:");

        jlFila.setText("Fila:");

        jLabel3.setText("Columna:");

        jLabel4.setText("Estado");

        jLabel5.setText("IdProyeccion:");

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbBuscar.setText("Buscar");

        jbActualizar.setText("Actualizar");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jbBorrar.setText("Borrar");
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jLabel1)
                .addContainerGap(244, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(jbBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(jbActualizar)
                        .addGap(27, 27, 27)
                        .addComponent(jbBorrar)
                        .addGap(18, 18, 18)
                        .addComponent(Limpiar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Opciones)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcbOpciones, 0, 312, Short.MAX_VALUE)
                                    .addComponent(jtfIdLugar)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlFila)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfFila)
                                    .addComponent(jtfColumna)
                                    .addComponent(jtfIdProyeccion)
                                    .addComponent(jcbEstado, 0, 312, Short.MAX_VALUE))))
                        .addGap(227, 227, 227))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Opciones))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfIdLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlFila)
                    .addComponent(jtfFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfColumna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfIdProyeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardar)
                    .addComponent(jbBuscar)
                    .addComponent(jbActualizar)
                    .addComponent(jbBorrar)
                    .addComponent(Limpiar))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbOpcionesActionPerformed
        String opciones = (String)jcbOpciones.getSelectedItem();
        switch(opciones){
            case "Guardar":
                jtfIdLugar.setEnabled(false);
                jtfFila.setEnabled(true);
                jtfColumna.setEnabled(true);
                jcbEstado.setEnabled(true);
                jtfIdProyeccion.setEnabled(true);
                jbGuardar.setEnabled(true);
                jbBuscar.setEnabled(false);
                jbActualizar.setEnabled(false);
                jbBorrar.setEnabled(false);
                break;
            case "Buscar":
                jtfIdLugar.setEnabled(true);
                jtfFila.setEnabled(false);
                jtfColumna.setEnabled(false);
                jcbEstado.setEnabled(false);
                jtfIdProyeccion.setEnabled(false);
                jbGuardar.setEnabled(false);
                jbBuscar.setEnabled(true);
                jbActualizar.setEnabled(false);
                jbBorrar.setEnabled(false);
                break;
            case "Actualizar":
                jtfIdLugar.setEnabled(true);
                jtfFila.setEnabled(true);
                jtfColumna.setEnabled(true);
                jcbEstado.setEnabled(true);
                jtfIdProyeccion.setEnabled(true);
                jbGuardar.setEnabled(false);
                jbBuscar.setEnabled(false);
                jbActualizar.setEnabled(true);
                jbBorrar.setEnabled(false);                
                break;
            case "Borrar":
                jtfIdLugar.setEnabled(true);
                jtfFila.setEnabled(false);
                jtfColumna.setEnabled(false);
                jcbEstado.setEnabled(false);
                jtfIdProyeccion.setEnabled(false);
                jbGuardar.setEnabled(false);
                jbBuscar.setEnabled(false);
                jbActualizar.setEnabled(false);
                jbBorrar.setEnabled(true);
                break;
        }
    }//GEN-LAST:event_jcbOpcionesActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        jtfIdLugar.setText("");
        jtfFila.setText("");
        jtfColumna.setText("");
        jtfIdProyeccion.setText("");
    }//GEN-LAST:event_LimpiarActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        //Validacion de campos vacios
        if(jtfIdLugar.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "El campos no puede estar vacio");
            return;
        }
        
        try{
            int idLugar = Integer.parseInt(jtfIdLugar.getText());
            lugarD.eliminarLugar(idLugar);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Error de formato" + e.getMessage());
        }
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        //Validacion de campos vacios
        if(jtfIdLugar.getText().trim().isEmpty() || jtfFila.getText().trim().isEmpty()
           || jtfColumna.getText().trim().isEmpty() || jtfIdProyeccion.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Los campos no pueden estar vacios");
            return;
        }
        
        try{
            int idLugar = Integer.parseInt(jtfIdLugar.getText());
            String fila = jtfFila.getText();
            int columna = Integer.parseInt(jtfColumna.getText());
            String estado = (String)jcbEstado.getSelectedItem();
            int idProyeccion = Integer.parseInt(jtfIdProyeccion.getText());

            Proyeccion proy = new Proyeccion();
            proy.setIdProyeccion(idProyeccion);

            LugarAsiento lugar = new LugarAsiento(idLugar, fila, columna, estado, proy);
            lugarD.actualizarLugar(lugar);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Error de formato" + e.getMessage());
        }
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        //Validacion de campos vacios
        if(jtfFila.getText().trim().isEmpty() || jtfColumna.getText().trim().isEmpty()
           || jtfIdProyeccion.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Los campos no pueden estar vacios");
            return;
        }
        
        try {
            String fila = jtfFila.getText();
            int columna = Integer.parseInt(jtfColumna.getText());
            String estado = (String)jcbEstado.getSelectedItem();
            int idProyeccion = Integer.parseInt(jtfIdProyeccion.getText());

            LugarAsiento lugar = new LugarAsiento();
            lugar.setFila(fila);
            lugar.setNumero(columna);
            lugar.setEstado(estado);

            Proyeccion proy = new Proyeccion();
            proy.setIdProyeccion(idProyeccion);

            lugar.setProyeccion(proy);
            lugarD.guardarLugar(lugar);
        }catch(NumberFormatException e){
             JOptionPane.showMessageDialog(this, "Error de formato" + e.getMessage());
        }
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void cargarOpciones(){
        jcbOpciones.addItem("Guardar");
        jcbOpciones.addItem("Buscar");
        jcbOpciones.addItem("Actualizar");
        jcbOpciones.addItem("Borrar");
    }
    
    private void cargarEstado(){
        jcbEstado.addItem("Ocupado");
        jcbEstado.addItem("Libre");
        jcbEstado.addItem("Deshabilitado");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpiar;
    private javax.swing.JLabel Opciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JComboBox<String> jcbEstado;
    private javax.swing.JComboBox<String> jcbOpciones;
    private javax.swing.JLabel jlFila;
    private javax.swing.JTextField jtfColumna;
    private javax.swing.JTextField jtfFila;
    private javax.swing.JTextField jtfIdLugar;
    private javax.swing.JTextField jtfIdProyeccion;
    // End of variables declaration//GEN-END:variables
}
