/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import entidades.Pelicula;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import persistencias.Conexion;
import persistencias.PeliculasData;

/**
 *
 * @author crb_p
 */
public class ListasPeliculas extends javax.swing.JInternalFrame {
    private PeliculasData peliData;
    private DefaultTableModel modeloTabla = new DefaultTableModel();

    public ListasPeliculas(Connection buscarConexion) {
    }
    Connection con = Conexion.buscarConexion();
    
    public ListasPeliculas() {
        initComponents();
        tablaCabecera();
        borrarFilasDeTabla();
        peliData = new PeliculasData(con);
    }

    private void borrarFilasDeTabla() {
        int indice = modeloTabla.getRowCount() - 1;

        for (int i = indice; i >= 0; i--) {
            modeloTabla.removeRow(i);
        }
    }

    private void tablaCabecera() {
        ArrayList<Object> filaCabercera = new ArrayList<>();
        modeloTabla.addColumn("Id Pelicula");
        modeloTabla.addColumn("Titulo");
        modeloTabla.addColumn("Director");
        modeloTabla.addColumn("Actores");
        modeloTabla.addColumn("Origen");
        modeloTabla.addColumn("Genero");
        modeloTabla.addColumn("Estreno");
        modeloTabla.addColumn("En Cartelera");
        for (Object it : filaCabercera) {
            modeloTabla.addColumn(it);
        }
        jTpeliculas.setModel(modeloTabla);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jRBcartelera = new javax.swing.JRadioButton();
        jRBestrenos = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTpeliculas = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("PELICULAS Y PROXIMOS ESTRENOS");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PELICULAS");

        jRBcartelera.setText("EN CARTELERA");
        jRBcartelera.setIcon(new javax.swing.ImageIcon("C:\\Users\\crb_p\\OneDrive\\Documentos\\practicos java\\ProyectoFinal_CinemaCentro_Gp9\\src\\iconos\\video_camera_play_icon_231646.png")); // NOI18N
        jRBcartelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBcarteleraActionPerformed(evt);
            }
        });

        jRBestrenos.setText("PROXIMOS ESTRENOS");
        jRBestrenos.setIcon(new javax.swing.ImageIcon("C:\\Users\\crb_p\\OneDrive\\Documentos\\practicos java\\ProyectoFinal_CinemaCentro_Gp9\\src\\iconos\\video_camera_play_icon_231646.png")); // NOI18N
        jRBestrenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBestrenosActionPerformed(evt);
            }
        });

        jTpeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane1.setViewportView(jTpeliculas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jRBcartelera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRBestrenos)
                .addGap(166, 166, 166))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBcartelera)
                    .addComponent(jRBestrenos))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBcarteleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBcarteleraActionPerformed
         borrarFilasDeTabla();
         jRBestrenos.setSelected(false);
         cargarDatosEnCartelera();
    }//GEN-LAST:event_jRBcarteleraActionPerformed

    private void jRBestrenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBestrenosActionPerformed
         borrarFilasDeTabla();
         jRBcartelera.setSelected(false);
         cargarEstrenos();
         
    }//GEN-LAST:event_jRBestrenosActionPerformed

    private void cargarDatosEnCartelera(){
       borrarFilasDeTabla();
       List<Pelicula> listaPelisCarterlera = peliData.listarPeliculasenCartelera();
        for (Pelicula peli : listaPelisCarterlera) {
            modeloTabla.addRow(new Object[]{
            peli.getIdPelicula(),
            peli.getTitulo(),
            peli.getDirector(),
            peli.getActores(),
            peli.getOrigen(),
            peli.getGenero(),
            peli.getEstreno(),
            peli.isEnCartelera()
            });
        }
    }
    
    private void cargarEstrenos(){
       borrarFilasDeTabla();
       List<Pelicula> listaEstrenos = peliData.estrenos();
        for (Pelicula peliEstreno : listaEstrenos) {
            modeloTabla.addRow(new Object[]{
            peliEstreno.getIdPelicula(),
            peliEstreno.getTitulo(),
            peliEstreno.getDirector(),
            peliEstreno.getActores(),
            peliEstreno.getOrigen(),
            peliEstreno.getGenero(),
            peliEstreno.getEstreno(),
            peliEstreno.isEnCartelera()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRBcartelera;
    private javax.swing.JRadioButton jRBestrenos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTpeliculas;
    // End of variables declaration//GEN-END:variables
}
