/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author crb_p
 */
public class VistaMenu extends javax.swing.JFrame {

    /**
     * Creates new form VistaMenu
     */
    public VistaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMIcartelera = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMIcompra = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMprueba = new javax.swing.JMenuItem();
        jMIregistro = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMIgestionPeliculas = new javax.swing.JMenuItem();
        jMIgestionSalas = new javax.swing.JMenuItem();
        jMIgestionTickets = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CinemaCentro");
        setAutoRequestFocus(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1443, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu2.setText("Peliculas");

        jMIcartelera.setText("Ver Cartelera y Proximos Estrenos");
        jMIcartelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIcarteleraActionPerformed(evt);
            }
        });
        jMenu2.add(jMIcartelera);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Compra Online");

        jMIcompra.setText("Comprar entradas");
        jMIcompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIcompraActionPerformed(evt);
            }
        });
        jMenu3.add(jMIcompra);

        jMenuItem3.setText("Detalles de compra");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMprueba.setText("compra prueba");
        jMprueba.setAutoscrolls(true);
        jMprueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMpruebaActionPerformed(evt);
            }
        });
        jMenu3.add(jMprueba);

        jMIregistro.setText("REGISTRATE !!!");
        jMIregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIregistroActionPerformed(evt);
            }
        });
        jMenu3.add(jMIregistro);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consultas");

        jMenuItem9.setText("Disponibilidad");
        jMenu4.add(jMenuItem9);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("Administracion");

        jMIgestionPeliculas.setText("Peliculas");
        jMIgestionPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIgestionPeliculasActionPerformed(evt);
            }
        });
        jMenu1.add(jMIgestionPeliculas);

        jMIgestionSalas.setText("Salas");
        jMIgestionSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIgestionSalasActionPerformed(evt);
            }
        });
        jMenu1.add(jMIgestionSalas);

        jMIgestionTickets.setText("Tickets");
        jMIgestionTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIgestionTicketsActionPerformed(evt);
            }
        });
        jMenu1.add(jMIgestionTickets);

        jMenuItem11.setBackground(new java.awt.Color(0, 51, 0));
        jMenuItem11.setText("Compradores");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuItem12.setText("Proyecciones");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuItem14.setText("Lugares");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem14);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Estadisticas");

        jMenuItem15.setText("Ver Estadisticas");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem15);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        AdmiCompradores admiCompra = new AdmiCompradores();
        admiCompra.setVisible(true);
        escritorio.add(admiCompra);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        AdmiProyecciones admiProy = new AdmiProyecciones();
        admiProy.setVisible(true);
        escritorio.add(admiProy);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        AdmiLugares admiLugar = new AdmiLugares();
        admiLugar.setVisible(true);
        escritorio.add(admiLugar);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMIcarteleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIcarteleraActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ListasPeliculas listarpeliculas = new ListasPeliculas();
        listarpeliculas.setVisible(true);
        escritorio.add(listarpeliculas);
    }//GEN-LAST:event_jMIcarteleraActionPerformed

    private void jMIgestionPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIgestionPeliculasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaPeliculas vistapelis = new VistaPeliculas();
        vistapelis.setVisible(true);
        escritorio.add(vistapelis);
    }//GEN-LAST:event_jMIgestionPeliculasActionPerformed

    private void jMIcompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIcompraActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        GestionCompraDeTickets compra = new GestionCompraDeTickets();
        compra.setVisible(true);
        escritorio.add(compra);
    }//GEN-LAST:event_jMIcompraActionPerformed

    private void jMIgestionSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIgestionSalasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        GestionSalas salas = new GestionSalas();
        salas.setVisible(true);
        escritorio.add(salas);
    }//GEN-LAST:event_jMIgestionSalasActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaEstadisticas est = new VistaEstadisticas();
        est.setVisible(true);
        escritorio.add(est);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaDetalleTicket detalles = new VistaDetalleTicket();
        detalles.setVisible(true);
        escritorio.add(detalles);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMpruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMpruebaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaCompra comp = new VistaCompra();
        comp.setVisible(true);
        escritorio.add(comp); 
    }//GEN-LAST:event_jMpruebaActionPerformed

    private void jMIgestionTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIgestionTicketsActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        GestionTikets gestionTicket = new GestionTikets();
        gestionTicket.setVisible(true);
        escritorio.add(gestionTicket); 
    }//GEN-LAST:event_jMIgestionTicketsActionPerformed

    private void jMIregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIregistroActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaRegistro reg = new VistaRegistro();
        reg.setVisible(true);
        escritorio.add(reg);
    }//GEN-LAST:event_jMIregistroActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jMIcartelera;
    private javax.swing.JMenuItem jMIcompra;
    private javax.swing.JMenuItem jMIgestionPeliculas;
    private javax.swing.JMenuItem jMIgestionSalas;
    private javax.swing.JMenuItem jMIgestionTickets;
    private javax.swing.JMenuItem jMIregistro;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMprueba;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
